### ISSUE TITLE
Add Vision Tracking of Gear Target

### ISSUE THREAD

**Issue by dracco1993** [RAR1741/RA17_RobotCode#14]
We need to more fully flesh out the vision tracking of the gear target:
- [x] Add retro-reflective tape in the correct configuration
- [ ] Recalibrate camera settings
- [ ] Add code to center the target in the field of vision using the drive train

**Comment by snydecor000** [comment]
This has been pushed back to competition two due to lack of testing of vision tracking...and or tracking at all
